#!/bin/bash -l
#SBATCH --constraint=knl
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:30:00
#SBATCH --cpu-freq=1400000
#SBATCH --job-name=job-1c
#SBATCH --output=stats/job-1c.o%j
#SBATCH --error=stats/job-1c.e%j

# set some openmp variables: 
# OMP_PLACES=threads maps OpenMP threads to hardware threads
# OMP_PROC_BIND=spread binds threads as evenly as possible
#
# see https://docs.nersc.gov/jobs/affinity/ for more information

export OMP_PLACES=threads
export OMP_PROC_BIND=spread

export OMP_SCHEDULE=static
# export OMP_SCHEDULE=dynamic

for t in 1
   do
   export OMP_NUM_THREADS=$t
   for r in 256
      do
      for p in 32
         do
         for b in 1 2 4
            do
            srun -n 1 build/ray -r $r -p $p -b $b
         done
      done
   done
done